### ISSUE TITLE
Sequence Type Inference Fails

### ISSUE THREAD

**Issue by Halithor** [fponticelli/partsing#9]
Using `sequence` gives you type errors without explicit typing of the sequence function.

This example `sequence(match('@'))` gives a type error, when it should be inferred as `<TextInput, string[], DecodeError>`. The error is 
```
Argument of type 'Decoder<TextInput, "@", DecodeError>' is not assignable to parameter of type 'Decoder<{}, "@", {}>'.
  Types of property 'run' are incompatible.
    Type 'Decoding<TextInput, "@", DecodeError>' is not assignable to type 'Decoding<{}, "@", {}>'.
      Types of parameters 'input' and 'input' are incompatible.
        Type '{}' is not assignable to type 'TextInput'.
```

The workaround is to provide the explicit typing annotation to `sequence`. For the example above you can do `sequence<TextInput, string[], DecodeError>(...)`.

**Comment by fponticelli** [comment]
The type signature has changed and it is backward incompatible but at least it appears to be inferred correctly for both `sequence` and `oneOf`.
